server:
  port : 8080

  
spring :
  #### DB
  datasource :
    driver-class-name : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/bms
#    url : jdbc:mariadb://localhost:3306/korea
#    url : jdbc:mariadb://localhost:3306/hoteltest
    username : kj
    password : 123456
    
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: hotelbomulsum
#    password: jspajakwfbcgijxg
#    ##password: Bomulsum1230  
#    properties:
#      mail:
#        smtp:
#          auth: true
#         starttls:
#           enable: true
    
  ### 내용 갱신 시 서버 reloading
  devtools :
    livereload :
      enabled : true
      
      
  ### view page
  mvc :
    view :
      prefix : /views/
      suffix : .jsp
      
      
      
###mybatis 설정
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: bms.db 

##jspajakwfbcgijxg  
##spring.mail.host=smtp.gmail.com spring.mail.port=587 spring.mail.username= hotelbomulsum@gmail.com // gmail 계정
##spring.mail.password=jspajakwfbcgijxg // 앱 비밀번호 spring.mail.properties.mail.smtp.auth=true
##spring.mail.properties.mail.smtp.timeout=5000 spring.mail.properties.mail.smtp.starttls.enable=true 



#JavaMailSender 설정

mail:
  smtp:
    port : 465
    auth : true
    starttls :
      required : true
      enable : true
    socketFactory : 
      class : javax.net.ssl.SSLSocketFactory
      fallback : false
      port : 465

#admin 구글 계정 id, password
AdminMail : 
  id : hotelbomulsum@gmail.com
  password : vcrjahznqhdjjqov
#Bomulsum1230 




